name: regress gfarm2fs

on:
  push:
  pull_request:

jobs:

  regress:
    name: Run regress with gfarm2fs
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-26.04-arm]
    runs-on: ${{ matrix.runner }}

    steps:
      - name: checkout gfarm
        uses: actions/checkout@v4
        with:
          repository: oss-tsukuba/gfarm
          path: gfarm

      - name: checkout gfarm2fs
        uses: actions/checkout@v4
        with:
          path: gfarm/gfarm2fs

      - name: docker compose build
        id: compose
        run: |
          cd gfarm/docker/dist
          sh ./minica.sh
          docker compose build --build-arg UID=$(id -u) c1

      - name: docker compose up
        id: up
        run: |
          cd gfarm/docker/dist
          docker compose up -d

      - name: build_all
        id: build_all
        run: |
          cd gfarm/docker/dist
          docker exec -u ${USER} -w /home/${USER}/gfarm/docker/dist gfarm-c1 \
             sh ./all.sh

      # - name: regress_gfarm
      #   id: regress_gfarm
      #   run: |
      #     cd gfarm/docker/dist
      #     docker exec -u ${USER} -w /home/${USER}/gfarm/docker/dist gfarm-c1 \
      #        sh ./regress.sh

      - name: regress_gfarm2fs
        id: regress_gfarm2fs
        run: |
          set -o pipefail
          mkdir -p regress-log
          AUTH=$(docker exec -u ${USER} gfarm-c1 gfhost -lv | head -1 | awk '{ print $2 }')
          DIST=$(docker exec -u ${USER} gfarm-c1 gfarm.arch.guess)
          DATE=$(date +%F.%H_%M_%S)
          docker exec -u ${USER} -w /home/${USER}/gfarm/docker/dist gfarm-c1 \
             sh ./regress-xattr.sh | tee regress-log/log.regress-xattr.$AUTH.$DIST.$DATE

      # - name: extract log files from the container
      #   if: always()
      #   run: |
      #     mkdir -p regress-log
      #     DIST=$(docker exec gfarm-c1 gfarm.arch.guess)
      #     docker exec -u ${USER} -w /home/${USER}/gfarm/build-${DIST}/regress \
      #         gfarm-c1 sh -c 'tar cf - log.*' | ( cd regress-log && tar pxf - ) || true

      - name: upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regress-log
          path: regress-log/*
